const colors = {
  primaryColor = '#FFF',
  actionColor = '#0775b5',
  progressBarColor = '#979797',
  borderPrimary = '#171616',
  backgroundDefault = '#FFF',
  defaultTextColor = '#171616',
  defaultIconColor = '#666',
  disableColor = '#999',
  topAlertColor = '#777',
  toastColor = '#333',
  toastTextColor = '#FFF',
  classListBackgroundColor = '#EEE',
  placeholderTextColor = '#CCC',
  getSubscriberModalColor = '#979797',
  paginationDotColor = '#369fdd',
  paginationInactiveDotColor = '#979797',
  accountIconColor = '#AAA',
  activeMenuColor = '#369fdd',
  refresherColor = '#979797',
  containerColor = '#EEE',
  defaultButtonColor = '#369fdd',
  defaultUserInfo = '#979797',
  defaultButtonTextColor = '#EEE',
  transparentButtonTextColor = '#369fdd',
  defaultInputColor = '#EEE',
  defaultLabelColor = '#333',
  disabledColor = '#555',
}

export default colors;